version: "3"
services:
  web:
    container_name: docker-prototyp
    image: "node:16-alpine"
    ports: [8080:8080]
    working_dir: /home/node/app
    user: "node"
    volumes:
      - ./:/home/node/app
    command: sh -c "npm install && npx eleventy --serve"


